server:
  session:
    cookie:
      http-only: true
  port: 8080

spring:
  cache:
    type: redis

  datasource:
    url: jdbc:mysql://localhost:3306/shop?useUnicode=true&characterEncoding=utf-8
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver

  thymeleaf:
    cache: false

mybatis:
  typeAliasesPackage: com.thunisoft.pojo
  mapper-locations: classpath:mapper/*.xml

